//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exact_Ferret.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AUTO_UPDATE {
            get {
                return ((bool)(this["AUTO_UPDATE"]));
            }
            set {
                this["AUTO_UPDATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public decimal INTERVAL_MINUTES {
            get {
                return ((decimal)(this["INTERVAL_MINUTES"]));
            }
            set {
                this["INTERVAL_MINUTES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\Exact Ferret\\Logs\\ef.log")]
        public string LOG_FILE_LOCATION {
            get {
                return ((string)(this["LOG_FILE_LOCATION"]));
            }
            set {
                this["LOG_FILE_LOCATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal LOG_ROLLOVER_KBYTES {
            get {
                return ((decimal)(this["LOG_ROLLOVER_KBYTES"]));
            }
            set {
                this["LOG_ROLLOVER_KBYTES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int LOG_LEVEL {
            get {
                return ((int)(this["LOG_LEVEL"]));
            }
            set {
                this["LOG_LEVEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\Exact Ferret\\Pictures")]
        public string IMAGE_LOCATION {
            get {
                return ((string)(this["IMAGE_LOCATION"]));
            }
            set {
                this["IMAGE_LOCATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CHANGE_WALLPAPER {
            get {
                return ((bool)(this["CHANGE_WALLPAPER"]));
            }
            set {
                this["CHANGE_WALLPAPER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CHANGE_LOCK_SCREEN {
            get {
                return ((bool)(this["CHANGE_LOCK_SCREEN"]));
            }
            set {
                this["CHANGE_LOCK_SCREEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public decimal MAX_OLD_IMAGES {
            get {
                return ((decimal)(this["MAX_OLD_IMAGES"]));
            }
            set {
                this["MAX_OLD_IMAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public decimal MINIMUM_IMAGE_WIDTH {
            get {
                return ((decimal)(this["MINIMUM_IMAGE_WIDTH"]));
            }
            set {
                this["MINIMUM_IMAGE_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("768")]
        public decimal MINIMUM_IMAGE_HEIGHT {
            get {
                return ((decimal)(this["MINIMUM_IMAGE_HEIGHT"]));
            }
            set {
                this["MINIMUM_IMAGE_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public decimal MINIMUM_IMAGE_RATIO {
            get {
                return ((decimal)(this["MINIMUM_IMAGE_RATIO"]));
            }
            set {
                this["MINIMUM_IMAGE_RATIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public decimal MAXIMUM_IMAGE_RATIO {
            get {
                return ((decimal)(this["MAXIMUM_IMAGE_RATIO"]));
            }
            set {
                this["MAXIMUM_IMAGE_RATIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SEARCH_TERM_MODIFIER {
            get {
                return ((string)(this["SEARCH_TERM_MODIFIER"]));
            }
            set {
                this["SEARCH_TERM_MODIFIER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal DOWNLOAD_ATTEMPTS {
            get {
                return ((decimal)(this["DOWNLOAD_ATTEMPTS"]));
            }
            set {
                this["DOWNLOAD_ATTEMPTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SAFE_SEARCH {
            get {
                return ((bool)(this["SAFE_SEARCH"]));
            }
            set {
                this["SAFE_SEARCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COLORS_IN_IMAGE {
            get {
                return ((int)(this["COLORS_IN_IMAGE"]));
            }
            set {
                this["COLORS_IN_IMAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TYPE_OF_IMAGE {
            get {
                return ((int)(this["TYPE_OF_IMAGE"]));
            }
            set {
                this["TYPE_OF_IMAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SEARCH_DOMAIN {
            get {
                return ((string)(this["SEARCH_DOMAIN"]));
            }
            set {
                this["SEARCH_DOMAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WALLPAPER_STYLE {
            get {
                return ((int)(this["WALLPAPER_STYLE"]));
            }
            set {
                this["WALLPAPER_STYLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999")]
        public decimal MAXIMUM_IMAGE_WIDTH {
            get {
                return ((decimal)(this["MAXIMUM_IMAGE_WIDTH"]));
            }
            set {
                this["MAXIMUM_IMAGE_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999")]
        public decimal MAXIMUM_IMAGE_HEIGHT {
            get {
                return ((decimal)(this["MAXIMUM_IMAGE_HEIGHT"]));
            }
            set {
                this["MAXIMUM_IMAGE_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%EXACTFERRET%\\dictionary.txt")]
        public string DICTIONARY_FILE {
            get {
                return ((string)(this["DICTIONARY_FILE"]));
            }
            set {
                this["DICTIONARY_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal HTTP_REQUEST_TIMEOUT {
            get {
                return ((decimal)(this["HTTP_REQUEST_TIMEOUT"]));
            }
            set {
                this["HTTP_REQUEST_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal LOG_RETENTION_DAYS {
            get {
                return ((decimal)(this["LOG_RETENTION_DAYS"]));
            }
            set {
                this["LOG_RETENTION_DAYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal INTERVAL_SECONDS {
            get {
                return ((decimal)(this["INTERVAL_SECONDS"]));
            }
            set {
                this["INTERVAL_SECONDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection BLOCKED_IMAGES {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BLOCKED_IMAGES"]));
            }
            set {
                this["BLOCKED_IMAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection BLOCKED_DOMAINS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BLOCKED_DOMAINS"]));
            }
            set {
                this["BLOCKED_DOMAINS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GOOGLE_API_KEY {
            get {
                return ((string)(this["GOOGLE_API_KEY"]));
            }
            set {
                this["GOOGLE_API_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool API_LIMIT_WARNING {
            get {
                return ((bool)(this["API_LIMIT_WARNING"]));
            }
            set {
                this["API_LIMIT_WARNING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CYCLE_AT_API_LIMIT {
            get {
                return ((bool)(this["CYCLE_AT_API_LIMIT"]));
            }
            set {
                this["CYCLE_AT_API_LIMIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-04-03")]
        public global::System.DateTime SUNDAY_START {
            get {
                return ((global::System.DateTime)(this["SUNDAY_START"]));
            }
            set {
                this["SUNDAY_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/03/2014 23:59:59")]
        public global::System.DateTime SUNDAY_STOP {
            get {
                return ((global::System.DateTime)(this["SUNDAY_STOP"]));
            }
            set {
                this["SUNDAY_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-04-03")]
        public global::System.DateTime MONDAY_START {
            get {
                return ((global::System.DateTime)(this["MONDAY_START"]));
            }
            set {
                this["MONDAY_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/03/2014 23:59:59")]
        public global::System.DateTime MONDAY_STOP {
            get {
                return ((global::System.DateTime)(this["MONDAY_STOP"]));
            }
            set {
                this["MONDAY_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-04-03")]
        public global::System.DateTime TUESDAY_START {
            get {
                return ((global::System.DateTime)(this["TUESDAY_START"]));
            }
            set {
                this["TUESDAY_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/03/2014 23:59:59")]
        public global::System.DateTime TUESDAY_STOP {
            get {
                return ((global::System.DateTime)(this["TUESDAY_STOP"]));
            }
            set {
                this["TUESDAY_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-04-03")]
        public global::System.DateTime WEDNESDAY_START {
            get {
                return ((global::System.DateTime)(this["WEDNESDAY_START"]));
            }
            set {
                this["WEDNESDAY_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/03/2014 23:59:59")]
        public global::System.DateTime WEDNESDAY_STOP {
            get {
                return ((global::System.DateTime)(this["WEDNESDAY_STOP"]));
            }
            set {
                this["WEDNESDAY_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-04-03")]
        public global::System.DateTime THURSDAY_START {
            get {
                return ((global::System.DateTime)(this["THURSDAY_START"]));
            }
            set {
                this["THURSDAY_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/03/2014 23:59:59")]
        public global::System.DateTime THURSDAY_STOP {
            get {
                return ((global::System.DateTime)(this["THURSDAY_STOP"]));
            }
            set {
                this["THURSDAY_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-04-03")]
        public global::System.DateTime FRIDAY_START {
            get {
                return ((global::System.DateTime)(this["FRIDAY_START"]));
            }
            set {
                this["FRIDAY_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/03/2014 23:59:59")]
        public global::System.DateTime FRIDAY_STOP {
            get {
                return ((global::System.DateTime)(this["FRIDAY_STOP"]));
            }
            set {
                this["FRIDAY_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-04-03")]
        public global::System.DateTime SATURDAY_START {
            get {
                return ((global::System.DateTime)(this["SATURDAY_START"]));
            }
            set {
                this["SATURDAY_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/03/2014 23:59:59")]
        public global::System.DateTime SATURDAY_STOP {
            get {
                return ((global::System.DateTime)(this["SATURDAY_STOP"]));
            }
            set {
                this["SATURDAY_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DO_NOT_OVERWRITE_BLOCKED_PICTURES {
            get {
                return ((bool)(this["DO_NOT_OVERWRITE_BLOCKED_PICTURES"]));
            }
            set {
                this["DO_NOT_OVERWRITE_BLOCKED_PICTURES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SETTINGS_SCHEDULE {
            get {
                return ((string)(this["SETTINGS_SCHEDULE"]));
            }
            set {
                this["SETTINGS_SCHEDULE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DONT_RUN_ON_BATTERY {
            get {
                return ((bool)(this["DONT_RUN_ON_BATTERY"]));
            }
            set {
                this["DONT_RUN_ON_BATTERY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BING_ACCESS_TOKEN {
            get {
                return ((string)(this["BING_ACCESS_TOKEN"]));
            }
            set {
                this["BING_ACCESS_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SINGLE_API_LIMIT_WARNING {
            get {
                return ((bool)(this["SINGLE_API_LIMIT_WARNING"]));
            }
            set {
                this["SINGLE_API_LIMIT_WARNING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Google</string>\r\n  <string>Bing</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SEARCH_ENGINE_ORDER {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SEARCH_ENGINE_ORDER"]));
            }
            set {
                this["SEARCH_ENGINE_ORDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PANIC_IMAGE {
            get {
                return ((string)(this["PANIC_IMAGE"]));
            }
            set {
                this["PANIC_IMAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QUICK_RUN_SHORTCUT {
            get {
                return ((int)(this["QUICK_RUN_SHORTCUT"]));
            }
            set {
                this["QUICK_RUN_SHORTCUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int PANIC_SHORTCUT {
            get {
                return ((int)(this["PANIC_SHORTCUT"]));
            }
            set {
                this["PANIC_SHORTCUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SETTINGS_SHORTCUT {
            get {
                return ((int)(this["SETTINGS_SHORTCUT"]));
            }
            set {
                this["SETTINGS_SHORTCUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SHOW_CAPTION {
            get {
                return ((bool)(this["SHOW_CAPTION"]));
            }
            set {
                this["SHOW_CAPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SHOW_DOMAIN {
            get {
                return ((bool)(this["SHOW_DOMAIN"]));
            }
            set {
                this["SHOW_DOMAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SHOW_TERM {
            get {
                return ((bool)(this["SHOW_TERM"]));
            }
            set {
                this["SHOW_TERM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DESKTOP_LABEL_LOCATION {
            get {
                return ((int)(this["DESKTOP_LABEL_LOCATION"]));
            }
            set {
                this["DESKTOP_LABEL_LOCATION"] = value;
            }
        }
    }
}
